# Generated by Django 3.0.1 on 2020-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0005_auto_20200710_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
